name: ci

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [dev]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: check for gdscript parse errors
        uses: chickensoft-games/godot-ci@v1
        with:
          godot-version: "4.4.1"
          project-path: .
          run: |
            godot --headless --quit --check-only
